<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tab Release Sales Order</name>
   <tag></tag>
   <elementGuidId>90e036ba-9103-4e0f-8a5a-07751d6bbf5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Sales$Menu']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>09a272d7-e3a7-4448-a69e-ec835d5e1e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/program/release-salesorder</value>
      <webElementGuid>94a7a6d3-e705-4a7b-9e81-cede0fc4e90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Release Sales Order</value>
      <webElementGuid>f7a1e13f-85b5-4db9-9abd-1b96f2602b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Sales$Menu&quot;)/li[@class=&quot;ant-menu-item&quot;]/a[1]</value>
      <webElementGuid>0486aa9e-0ebf-41cc-b3ab-228052a30738</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Sales$Menu']/li[2]/a</value>
      <webElementGuid>9669007a-84fe-4c2c-963b-4d5c602ecaaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Release Sales Order')]</value>
      <webElementGuid>2218d910-e518-4ab7-a981-78189c72ecd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Order'])[1]/following::a[1]</value>
      <webElementGuid>f1b68910-834f-4f22-866d-d102a0d064db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounting &amp; Finance'])[1]/following::a[2]</value>
      <webElementGuid>8c3a44bd-5dbc-4aab-b5f7-da3ee31c7448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Release Sales Order - Approval'])[2]/preceding::a[1]</value>
      <webElementGuid>402fb0b5-a62b-4bcf-806c-2946f64fcac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Release Kuota Cadangan'])[1]/preceding::a[2]</value>
      <webElementGuid>6da666d5-eba4-419a-98ac-df9f9194399b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Release Sales Order']/parent::*</value>
      <webElementGuid>146994a3-dc38-4e10-825a-4915d3c93aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/program/release-salesorder')])[3]</value>
      <webElementGuid>933df785-7ad7-4ab7-a120-14969f36907c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/ul/li[2]/a</value>
      <webElementGuid>4a41eae3-e38c-4821-81a4-c00105202d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/program/release-salesorder' and (text() = 'Release Sales Order' or . = 'Release Sales Order')]</value>
      <webElementGuid>78bc936f-3b3e-4083-b0d1-c6d70646370f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
