<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>303 - Sujadi</name>
   <tag></tag>
   <elementGuidId>6d349f4c-4159-46e2-a268-af6fcafc1387</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[contains(text(),'303 - Sujadi')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ant-select-dropdown-menu-item.ant-select-dropdown-menu-item-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>688102cc-e804-49d9-bae1-af5e59caa2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>270e5042-c182-4757-90f7-5b78785f6370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>843da3b2-fd7f-4906-9bbe-3fd133f6c76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-dropdown-menu-item ant-select-dropdown-menu-item-active</value>
      <webElementGuid>b6fe4ee9-399d-4fa4-8b4a-7212307483a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8b25ca49-5012-4aaa-bce0-f25a01772de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>303 - Sujadi</value>
      <webElementGuid>d673b823-5528-4d25-890d-ec8691619398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;40e9ac92-0333-41a1-e6ce-85d55a9079ce&quot;)/ul[@class=&quot;ant-select-dropdown-menu  ant-select-dropdown-menu-root ant-select-dropdown-menu-vertical&quot;]/li[@class=&quot;ant-select-dropdown-menu-item ant-select-dropdown-menu-item-active&quot;]</value>
      <webElementGuid>25da7a9e-87d7-4f3a-a48d-88f01678cbb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='40e9ac92-0333-41a1-e6ce-85d55a9079ce']/ul/li</value>
      <webElementGuid>12ad1c15-52d2-4061-8e4e-c2ebbf9973d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alokasi Piutang'])[1]/following::li[1]</value>
      <webElementGuid>ea7a15e8-2794-47a5-896c-8e6480b2a7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retur'])[1]/following::li[2]</value>
      <webElementGuid>93f89630-5fd6-4796-9b06-f272c9d18cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='303 - Sujadi']/parent::*</value>
      <webElementGuid>1e693550-9723-4383-9b58-737c0a45fa56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/ul/li</value>
      <webElementGuid>61a2db3b-1e9e-42e7-9cce-48d8c5686124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '303 - Sujadi' or . = '303 - Sujadi')]</value>
      <webElementGuid>45ff3d9b-49a9-480e-a8ae-a3af6030808a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
