<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Surat Jalan</name>
   <tag></tag>
   <elementGuidId>85670a48-0b8e-496e-a0d0-ec625c1a4539</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='add']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;add&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ef82dda-cded-43b7-aa52-4da44197101c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>6da58f93-8f3a-483f-a12d-2ccb79a9f242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>79d9642b-f236-4e35-9597-1a9306258ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-primary</value>
      <webElementGuid>766c5c29-4754-4734-bb30-4d992c71b6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>d87c7016-09a7-46c1-ab56-d6067d155e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-app&quot;)/div[@class=&quot;container&quot;]/main[@class=&quot;layout&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;canvas&quot;]/div[@class=&quot;canvas--content deliveryorder&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-row-flex ant-row-flex-start ant-row-flex-top&quot;]/div[@class=&quot;ant-col ant-col-xs-24 ant-col-lg-12&quot;]/div[@class=&quot;ant-btn-group&quot;]/button[@class=&quot;ant-btn ant-btn-primary&quot;]</value>
      <webElementGuid>c5ab3e08-8162-4bcb-9008-e054ed08b42e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='add']</value>
      <webElementGuid>0fd02203-8f16-4089-819c-125b80919d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-app']/div/main/section/div/div[2]/div[2]/div/div/div/button</value>
      <webElementGuid>8f1885d0-7bce-4964-a5b3-2cf438af94ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/following::button[1]</value>
      <webElementGuid>77b197cf-a569-4723-b2ba-1f095e40a1c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surat Jalan / Delivery Order'])[2]/following::button[1]</value>
      <webElementGuid>7dc3f885-e072-42e7-b99e-86197f8fe3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export CSV'])[1]/preceding::button[1]</value>
      <webElementGuid>44e97e0d-38fa-450e-818a-aca654e8f2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>63e35057-90e6-48c8-9a34-a37ebae3205a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'add' and @type = 'button' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>779bfa78-c0b6-4500-90be-e358860d0dca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
