<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filters</name>
   <tag></tag>
   <elementGuidId>ee453c9f-319f-4976-9c88-0d4a1322a36d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='react-app']/div[1]/main[1]/section[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
