<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Tanggal Kirim</name>
   <tag></tag>
   <elementGuidId>40b0fee4-ae2a-4ad6-b6fa-6cf519ebb135</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ant-calendar-picker-input.ant-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[17]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>368490d8-3d63-4988-a05f-2524c6b070b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select date</value>
      <webElementGuid>a38caf1a-63a3-4ab3-9a55-e81bedd8d90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-calendar-picker-input ant-input</value>
      <webElementGuid>99c294ca-931b-4547-b3ad-91798dad46d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ant-scrolling-effect&quot;]/div[10]/div[@class=&quot;ant-modal-root&quot;]/div[@class=&quot;ant-modal-wrap&quot;]/div[@class=&quot;ant-modal user-access__details-modal&quot;]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col&quot;]/div[@class=&quot;ant-row ant-form-item&quot;]/div[@class=&quot;ant-col ant-form-item-control-wrapper&quot;]/div[@class=&quot;ant-form-item-control&quot;]/span[@class=&quot;ant-form-item-children&quot;]/div[@class=&quot;picker&quot;]/span[@class=&quot;picker__container  ant-calendar-picker ant-calendar-picker-default&quot;]/div[1]/input[@class=&quot;ant-calendar-picker-input ant-input&quot;]</value>
      <webElementGuid>afc8cd1f-df45-42a5-993e-c1bf12a3a9ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[17]</value>
      <webElementGuid>d87a8335-0a08-4a7b-9512-1ea58d32eb61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/input</value>
      <webElementGuid>4dffcadb-113d-4a43-ba7b-3e76d6adddb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Select date']</value>
      <webElementGuid>16d4f783-7b6e-4f68-811d-62300b50d8a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
