<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_login</name>
   <tag></tag>
   <elementGuidId>9d9988f5-9cc1-4d00-b56c-b8d97678cbb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='login-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;login-btn&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5b5cafb3-907a-4e62-9431-6a56e05eff30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login-btn</value>
      <webElementGuid>4e76c353-8d78-4cca-9f83-317021908acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8539ae2f-b929-48f0-86df-c4acb363448d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-primary</value>
      <webElementGuid>4dd25680-233f-462b-aaa0-8c9621f58188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>dc5de4bb-9ddd-492f-8236-886d61fc66de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-app&quot;)/div[@class=&quot;container&quot;]/main[@class=&quot;layout&quot;]/section[@class=&quot;content content--logged-out&quot;]/div[@class=&quot;ant-row-flex ant-row-flex-center ant-row-flex-middle login&quot;]/div[@class=&quot;ant-col login__form ant-col-xs-22 ant-col-sm-12 ant-col-md-10 ant-col-lg-8 ant-col-xl-6&quot;]/form[1]/div[@class=&quot;login__form-login-btn&quot;]/button[@class=&quot;ant-btn ant-btn-primary&quot;]</value>
      <webElementGuid>0581701c-ccd1-409f-836e-289c14141556</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='login-btn']</value>
      <webElementGuid>789b227e-318a-4f42-926b-22a0675b738d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-app']/div/main/section/div/div/form/div[4]/button</value>
      <webElementGuid>72b08b9b-c311-4e4f-bd96-fe390c0f5352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>efa72749-41d3-4eff-8228-e60da2ca4e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'login-btn' and @type = 'submit' and (text() = 'login' or . = 'login')]</value>
      <webElementGuid>9b1b607c-49ec-4ba7-b5e2-e13524fe2378</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
