<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filters by Lot (Retur Barang Jadi)</name>
   <tag></tag>
   <elementGuidId>a0dfdb9b-b0ee-4406-b3f4-fd9a96ba4f4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[contains(text(),'Lot Retur Barang Jadi')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ant-select-dropdown-menu-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>96dcacbe-6672-4489-8970-e63c8d64a8d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>73242dd2-6c85-4a33-b6bb-81148435dffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>31a09854-6c39-449d-93b4-5ea8f5d8b5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Lot Retur Barang Jadi - 0 pcs</value>
      <webElementGuid>d884844b-2de5-4ed4-b596-d872de461e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-dropdown-menu-item</value>
      <webElementGuid>5cb46e22-4ba1-4154-9af8-ed7ba1b28cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9e285bf0-275a-483b-bca1-e786c9597e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b856fe0b-6998-42ad-9b12-a590db892155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lot Retur Barang Jadi - 0 pcs</value>
      <webElementGuid>7d958a0c-3c37-4928-bd1a-cf1d9ba8bfa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ab884fe0-083e-4aea-cc88-7fb1dc57afff&quot;)/ul[@class=&quot;ant-select-dropdown-menu  ant-select-dropdown-menu-root ant-select-dropdown-menu-vertical&quot;]/li[@class=&quot;ant-select-dropdown-menu-item&quot;]</value>
      <webElementGuid>f367e8a8-e680-4e21-a833-815dbfabb4da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ab884fe0-083e-4aea-cc88-7fb1dc57afff']/ul/li</value>
      <webElementGuid>c1eb3c10-de94-4bed-8e42-1877ee251fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::li[1]</value>
      <webElementGuid>86ff436d-97be-479d-ad6e-9192b6c3c6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::li[1]</value>
      <webElementGuid>1981d167-461e-4dda-9d8a-d511ce486fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lot WIP Untuk Mesin - 0 kg'])[1]/preceding::li[1]</value>
      <webElementGuid>ac91549f-fbef-436b-90b1-bc08d56fe3bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BPSP A 2 - 93144082 biji'])[1]/preceding::li[2]</value>
      <webElementGuid>c8ce985c-0b1c-4cd3-a8ed-72b52e0cecbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lot Retur Barang Jadi - 0 pcs']/parent::*</value>
      <webElementGuid>b5ec01e7-3fa9-4ac1-b3b7-7f1163f932a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/ul/li</value>
      <webElementGuid>5c8c3eb1-383d-4464-b4b8-16d3b284508e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@title = 'Lot Retur Barang Jadi - 0 pcs' and (text() = 'Lot Retur Barang Jadi - 0 pcs' or . = 'Lot Retur Barang Jadi - 0 pcs')]</value>
      <webElementGuid>20ce04b6-d42a-4327-9e7b-93367e94b5bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
