<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_By SPK_ant-checkbox-inner</name>
   <tag></tag>
   <elementGuidId>f2de7362-57f8-4064-8122-62f1d2038de7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ant-checkbox.ant-checkbox-checked.ant-checkbox-disabled > span.ant-checkbox-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-app']/div/main/section/div/div[2]/form/div/div/div[7]/div/div/div/div/span/div/div/label/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-checkbox-inner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-app&quot;)/div[@class=&quot;container&quot;]/main[@class=&quot;layout&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;canvas&quot;]/div[@class=&quot;canvas--content add-edit-view-data&quot;]/form[@class=&quot;data-form&quot;]/div[@class=&quot;ant-row-flex ant-row-flex-start ant-row-flex-top&quot;]/div[@class=&quot;ant-col ant-col-xs-24 ant-col-xs-order-2 ant-col-md-24 ant-col-md-order-1&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-11&quot;]/div[@class=&quot;ant-row ant-form-item&quot;]/div[@class=&quot;ant-col ant-form-item-control-wrapper&quot;]/div[@class=&quot;ant-form-item-control&quot;]/span[@class=&quot;ant-form-item-children&quot;]/div[@class=&quot;checkbox-group&quot;]/div[@class=&quot;ant-checkbox-group checkbox-group__container&quot;]/label[@class=&quot;checkbox-group__option  ant-checkbox-wrapper ant-checkbox-wrapper-checked ant-checkbox-wrapper-disabled&quot;]/span[@class=&quot;ant-checkbox ant-checkbox-checked ant-checkbox-disabled&quot;]/span[@class=&quot;ant-checkbox-inner&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-app']/div/main/section/div/div[2]/form/div/div/div[7]/div/div/div/div/span/div/div/label/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/span/div/div/label/span/span</value>
   </webElementXpaths>
</WebElementEntity>
